//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork12.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsOrders
    {
        public int ID { get; set; }
        public string IndexProduct { get; set; }
        public int IDOrder { get; set; }
        public int Count { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
