//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork12.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int IDUnitOfMeasurement { get; set; }
        public int Price { get; set; }
        public int IDProvider { get; set; }
        public int IDManufacturer { get; set; }
        public int IDCategory { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
    }
}
